#!/bin/bash
#SBATCH --job-name=migdal
#SBATCH --time=01:40:00
#SBATCH --partition=iric
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --array=0-50

source module

echo "start: `date`"
echo "job "$SLURM_ARRAY_TASK_ID

python3 xs.py $SLURM_ARRAY_TASK_ID

echo "end: `date`"
