#!/bin/bash
#SBATCH --job-name=acr
#SBATCH --time=03:30:00
#SBATCH --partition=iric
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=64000
#SBATCH --array=10-19

source ../module

echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
echo "^^^^^^^start: `date`"

echo "job "$SLURM_ARRAY_TASK_ID

python3 real_2d_sc.py $SLURM_ARRAY_TASK_ID

echo "^^^^^^^end: `date`"
