#!/bin/bash
#SBATCH --job-name=migdal
#SBATCH --time=04:00:00
#SBATCH --partition=iric
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1

#ml py-scipystack

#ml python/3.6.1
#ml py-scipystack/1.0_py36

source module

echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
echo "^^^^^^^start: `date`"

python3 Tc_nambu.py

echo "^^^^^^^end: `date`"
